services:
  - type: web
    name: bleep-that-shit
    plan: free # or 'starter', 'standard', etc. as needed
    # runtime: docker  # Optional; Render will auto-detect Dockerfile if present
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_ENV
        value: false
      - key: NODE_ENV
        value: false
      - key: RAILS_MASTER_KEY
        sync: false # Set this in the Render dashboard or as a secret
    autoDeploy: true
    branch: version-2-1
