// This file will be auto-generated by Supabase CLI
// For now, we define the types manually based on our schema

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          display_name: string | null;
          stripe_customer_id: string | null;
          subscription_tier: 'free' | 'starter' | 'pro' | 'team';
          subscription_status: 'active' | 'cancelled' | 'past_due' | null;
          subscription_ends_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          display_name?: string | null;
          stripe_customer_id?: string | null;
          subscription_tier?: 'free' | 'starter' | 'pro' | 'team';
          subscription_status?: 'active' | 'cancelled' | 'past_due' | null;
          subscription_ends_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          display_name?: string | null;
          stripe_customer_id?: string | null;
          subscription_tier?: 'free' | 'starter' | 'pro' | 'team';
          subscription_status?: 'active' | 'cancelled' | 'past_due' | null;
          subscription_ends_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          status: 'draft' | 'processing' | 'ready' | 'error';
          original_file_path: string | null;
          original_file_size: number | null;
          duration_seconds: number | null;
          transcription: Json | null;
          bleep_config: Json | null;
          processing_minutes: number | null;
          locked_by: string | null;
          locked_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          status?: 'draft' | 'processing' | 'ready' | 'error';
          original_file_path?: string | null;
          original_file_size?: number | null;
          duration_seconds?: number | null;
          transcription?: Json | null;
          bleep_config?: Json | null;
          processing_minutes?: number | null;
          locked_by?: string | null;
          locked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          status?: 'draft' | 'processing' | 'ready' | 'error';
          original_file_path?: string | null;
          original_file_size?: number | null;
          duration_seconds?: number | null;
          transcription?: Json | null;
          bleep_config?: Json | null;
          processing_minutes?: number | null;
          locked_by?: string | null;
          locked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      wordsets: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          words: string[];
          color: string | null;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          words: string[];
          color?: string | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          words?: string[];
          color?: string | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      usage: {
        Row: {
          id: string;
          user_id: string;
          billing_period_start: string;
          billing_period_end: string;
          minutes_used: number;
          minutes_limit: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          billing_period_start: string;
          billing_period_end: string;
          minutes_used?: number;
          minutes_limit: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          billing_period_start?: string;
          billing_period_end?: string;
          minutes_used?: number;
          minutes_limit?: number;
          created_at?: string;
        };
      };
      team_members: {
        Row: {
          id: string;
          project_id: string;
          user_id: string;
          role: 'owner' | 'editor' | 'viewer';
          invited_at: string;
          accepted_at: string | null;
        };
        Insert: {
          id?: string;
          project_id: string;
          user_id: string;
          role?: 'owner' | 'editor' | 'viewer';
          invited_at?: string;
          accepted_at?: string | null;
        };
        Update: {
          id?: string;
          project_id?: string;
          user_id?: string;
          role?: 'owner' | 'editor' | 'viewer';
          invited_at?: string;
          accepted_at?: string | null;
        };
      };
      jobs: {
        Row: {
          id: string;
          project_id: string;
          replicate_id: string | null;
          status: 'pending' | 'processing' | 'completed' | 'failed';
          error_message: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          replicate_id?: string | null;
          status?: 'pending' | 'processing' | 'completed' | 'failed';
          error_message?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          replicate_id?: string | null;
          status?: 'pending' | 'processing' | 'completed' | 'failed';
          error_message?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
